import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { SURVIVAL, SURVIVAL_BY_SEED, SURVIVAL_HOURS, SURVIVAL_PACE_MINUTES, SURVIVAL_SEED_BALANCE } from "../src/survival.js";

/**
 * docs/economy.md quotes survival figures to the reader, and the rent screen
 * quotes the same ones to a player about to spend money. Both must come from
 * src/survival.ts, which is generated by scripts/simulate-autoplay.ts --emit.
 * A figure typed in by hand, or left behind when the table was regenerated, is
 * the failure this guards against.
 */
describe("docs/economy.md", () => {
  const doc = readFileSync(new URL("../docs/economy.md", import.meta.url), "utf8");

  /** Every percentage the generated table could justify, to one decimal. */
  const generated = new Set<string>();
  for (const row of Object.values(SURVIVAL)) {
    for (const v of [row.overall, row.low, row.high, ...Object.values(row.byPreset)]) generated.add(v.toFixed(1));
  }
  for (const row of Object.values(SURVIVAL_BY_SEED)) for (const v of row) generated.add(v.toFixed(1));

  it("quotes no survival percentage that is not in the generated table", () => {
    const strays: string[] = [];
    for (const line of doc.split("\n")) {
      if (!line.trimStart().startsWith("|")) continue;
      for (const m of line.matchAll(/(\d+(?:\.\d)?)%/g)) {
        if (!generated.has(Number(m[1]).toFixed(1))) strays.push(`${m[0]} in: ${line.trim().slice(0, 72)}`);
      }
    }
    expect(strays).toEqual([]);
  });

  it("states every band's median time to bust as the generated table has it", () => {
    for (const [band, row] of Object.entries(SURVIVAL)) {
      if (row.medianHours === null) continue;
      expect(doc, `band ${band} median`).toContain(`${row.medianHours.toFixed(1)} h`);
    }
  });

  it("describes the basis the figures were measured on", () => {
    expect(doc).toContain(`${SURVIVAL_SEED_BALANCE}`);
    expect(doc).toMatch(new RegExp(`${SURVIVAL_PACE_MINUTES}\\s*min`, "i"));
    expect(doc).toContain(String(SURVIVAL_HOURS));
  });
});
