// Generated by scripts/simulate-autoplay.ts --emit. Do not edit by hand.
//
// How often a rental lasts a week of autoplay, measured over 20,000 agents per
// preset per band: one match every 10 minutes for 168 hours from a starting
// balance of 900, with no settlement clamp, stopping when the agent can no
// longer cover its band's worst match. Outcomes are exact, not sampled, and the
// run is seeded with 24301, so this file is reproducible: the same code always
// writes the same numbers.
//
// The rent screen and docs/economy.md both quote these, and neither may state a
// survival figure that is not in this file.
//
// Regenerate with: npx tsx scripts/simulate-autoplay.ts --emit
import type { PresetName } from "./presets.js";
import type { BandName } from "./db/schema.js";

export type BandSurvival = {
  /** Percentage of agents still playing after a week, across all presets. */
  overall: number;
  /** The worst and best preset in this band, for agents with no preset. */
  low: number;
  high: number;
  /** Half of the agents that busted had gone by here. */
  medianMatches: number | null;
  medianHours: number | null;
  byPreset: Record<PresetName, number>;
};

export const SURVIVAL_HOURS = 168;
export const SURVIVAL_PACE_MINUTES = 10;
export const SURVIVAL_SEED_BALANCE = 900;
/** The RNG seed this table was generated with. */
export const SURVIVAL_RNG_SEED = 24301;

export const SURVIVAL: Record<BandName, BandSurvival> = {
  A: {
    overall: 99.1,
    low: 98.5,
    high: 99.5,
    medianMatches: 851,
    medianHours: 141.8,
    byPreset: {
      Anchor: 99.2,
      Hammer: 99.5,
      Mirage: 98.5,
      Bully: 99.3,
    },
  },
  B: {
    overall: 80.6,
    low: 76.5,
    high: 84.4,
    medianMatches: 617,
    medianHours: 102.8,
    byPreset: {
      Anchor: 79.2,
      Hammer: 84.4,
      Mirage: 76.5,
      Bully: 82.2,
    },
  },
  C: {
    overall: 60.6,
    low: 56.1,
    high: 65.4,
    medianMatches: 441,
    medianHours: 73.5,
    byPreset: {
      Anchor: 58.6,
      Hammer: 65.4,
      Mirage: 56.1,
      Bully: 62.3,
    },
  },
};

/** What to tell someone renting this preset in this band, as a percentage. */
export function survivalFor(band: BandName, preset: PresetName | null): { low: number; high: number } {
  const row = SURVIVAL[band];
  if (preset === null) return { low: row.low, high: row.high };
  const exact = row.byPreset[preset];
  return { low: exact, high: exact };
}
